// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
import TomSelectController from "./tom_select_controller"

import {application} from "./application"

// application.register("hello", HelloController)
application.register("tom-select", TomSelectController)
